name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'kosolabs' }}
    permissions:
      contents: write
      id-token: write
    environment:
      name: axum-anyhow-release
    steps:
      - &checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install-rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy,rustfmt
      - uses: release-plz/action@v0.5.118
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'kosolabs' }}
    permissions:
      contents: write
      pull-requests: write
    environment:
      name: axum-anyhow-release
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *install-rust
      - uses: release-plz/action@v0.5.118
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
